### ISSUE TITLE
Pleaserun tarball on opscode has PAX extensions

### ISSUE THREAD

**Issue by davidski** [otakup0pe/chef-pleaserun#1]
The pleaserun cookbook as hosted at http://community.opscode.com/cookbooks/pleaserun looks to be created with PAX headers (perhaps with gtar or bsdtar?). Berkshelf 2.x on Windows platforms (cygwin) can't read the pax attributes and instead creates 10 different PaxHeader directories with regular files in them. These extra directories and files cause convergence to fail when the cookbook is uploaded and used. The current workaround is to manually delete the extra directories after each update, which is really awkward.

Can the tarball be regenerated to not have pax extensions?

**Comment by jolexa** [comment]
FYI, I'm having similar issue on RHEL6 with Berks 3.1.0. I cannot even upload the cookbook. I took @davidski advice and removed all the PaxHeader directories.

E, [2014-05-07T16:33:33.578277 #26590] ERROR -- : Cookbook file PaxHeader/metadata.rb has a ruby syntax error:
E, [2014-05-07T16:33:33.578399 #26590] ERROR -- : /home/jeremy.olexa/.berkshelf/cookbooks/pleaserun-0.1.0/PaxHeader/metadata.rb:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input

**Comment by pelletiermaxime** [comment]
A working workaround for me was to use the git version in my Berksfile:
cookbook 'pleaserun', git: 'https://github.com/paulczar/chef-pleaserun'

**Comment by otakup0pe** [comment]
This does not seem to be a thing with the version currently in supermarket.
