### ISSUE TITLE
Ohai conflicts with latest Chef

### ISSUE THREAD

**Issue by benkershner** [otakup0pe/chef-pleaserun#2]
The Ohai version set here (~> 6.20) conflicts with the Ohai version (7.0.4) in the latest Chef Client (11.12.8). I _think_ this means updating jordansissel's pleaserun gem first, and then this will work, but I'm not 100% sure (new to Ruby).

**Comment by pib** [comment]
I just ran into this same problem.

In theory all this would take is a `bundle update ohai` within pleaserun, but that's assuming no breaking changes have been introduced into version ohai 7...

**Comment by paulczar** [comment]
I believe this needs to be fixed here - https://github.com/jordansissel/pleaserun/blob/master/pleaserun.gemspec#L17

**Comment by rberger** [comment]
Any workarounds?

**Comment by rberger** [comment]
This seems to be fixed with the current version of pleaserun. Just tested it with pleaserun version 0.0.12

**Comment by otakup0pe** [comment]
This seems to be working fine on Chef 13 with what qualifies as a release candidate for this cookbook....
